### ISSUE TITLE
Refined Logo

### ISSUE THREAD

**Issue by TheJoeFin** [dotMorten/WinUIEx#102]
I was playing around in Figma and made a logo which is basically the same as what you have today, but the Ex is projected onto the WinUI Cube. If you're interested, I can refine it. 
![WinUIEx](https://user-images.githubusercontent.com/7809853/213562720-43f3e490-1e8c-494e-b509-a65a0d1223b8.png)

**Comment by dotMorten** [comment]
Thank you for this! This is really neat and an interesting idea. I did have one concern wrt how it would look getting into a tiny icon, and it led me to tweak the design inspired by yours:
![image](https://user-images.githubusercontent.com/1378165/213576735-5d19ad23-b7b7-43d5-9991-6b08447e198a.png)
Thoughts?

**Comment by TheJoeFin** [comment]
Love it! And you are totally right, your revised design would be recognizable on a 16x16 icon.

**Comment by dotMorten** [comment]
I’ll keep it open until I get a chance to wrap this up. Again thanks for the great inspiration

**Comment by dotMorten** [comment]
Done!
