### ISSUE TITLE
The `Backdrop` is cleared when the window cancel close

### ISSUE THREAD

**Issue by Wenveo** [dotMorten/WinUIEx#107]
When I set the ***args.Handle*** to ***true*** in the **Closed** event handler

Just like...

```
var window = new MainWindow();
window.Closed += OnClosed;

private void OnClosed(object sender, WindowEventArgs args)
{
    args.Handle = true;
}
```

The window is not close, But the `Backdrop` will be cleanup.
https://github.com/dotMorten/WinUIEx/blob/3173bb17e8fde2bcb1c75a7aa7e054327bf7ba92/src/WinUIEx/WindowManager.cs#L92-L96

**Comment by dotMorten** [comment]
Closing - Backdrop APIs has been deprecated in favor of Microsoft's own backdrop APIs
