### ISSUE TITLE
Cant set Dark theme

### ISSUE THREAD

**Issue by tinmac** [dotMorten/WinUIEx#108]
Hi @dotMorten I use WinUiE & its very usefull, many thanks for toolkit.

There is an issue with setting a WindowEx to the dark theme, it flashes/blinks Dark momentarily but remains Light. When i narrowed it down to WinUiEx I jumped here to see if WinUiEx supported theme changes in case there was a clash but this isnt the case.

[Here](https://github.com/tinmac/WinUiEx_ThemeTest) is a basic project to demonstrate the problem.

**Comment by tinmac** [comment]
Ok so now I see the `WindowContent` property. I have re-written the WindowEx ctor code 

from this
```
var content = this.Content as FrameworkElement;
content.RequestedTheme = ElementTheme.Dark;
```

To this
```
var content = this.WindowContent as FrameworkElement;
content.RequestedTheme = ElementTheme.Dark;
```

Which works but there is a blink/flash from light to dark when the window opens, is there a way to avoid/fix this?

**Comment by tinmac** [comment]
Closed as I dont think its anything to do with WinUiEx

**Comment by dotMorten** [comment]
The backdrop APIs has been removed in favor of the new Microsoft-provided APIs in v1.3 - let me know if you still see an issue, but in that case it's most likely a winappsdk issue.
