### ISSUE TITLE
WebAuthenticator Opens Second Instance of App (MAUI)

### ISSUE THREAD

**Issue by zizusoft** [dotMorten/WinUIEx#111]
In lieu of the MAUI WebAuthenticator issue (https://github.com/dotnet/maui/issues/2702)

I am trying to use this for my MAUI project with Windows.

![image](https://user-images.githubusercontent.com/54889301/222961268-2d431d63-1f41-4e86-a2b8-32518bf78e04.png)

It launches the web browser for authentication just fine - the only issue is that once I complete authentication, the web browser prompts me to relaunch my app - and creates a second instance of the App rather than returning to the original one that opened the browser.

![image](https://user-images.githubusercontent.com/54889301/222961317-9887c2f0-2b53-418a-9a5a-0f590af4347a.png)

![image](https://user-images.githubusercontent.com/54889301/222961344-fb9e6dad-2480-49c9-b3d0-1634fdc1cd12.png)

Have I missed something in the setup?

Thanks

**Comment by dotMorten** [comment]
App activation works by starting a new instance. WinUiEx should detect it’s meant for an existing instance and redirect the activation to that app and shut the new instance down. If that doesn’t happen it’s likely your oauth service is munging the state parameter that contains the information about your existing instance that the activation is meant for

**Comment by zizusoft** [comment]
Thanks for getting back to me so quickly.

I'm using Microsoft Azure's OAUTH 2 SSO....

I thought it best to try with your sample / example for MAUI just to prove it is an issue with Microsoft, and not WinUIEx / my setup.

Have the credentials changed from your sample, as If I used the supplied email and password, I get red outlines on the sign in box which I assume means the password is wrong?

![image](https://user-images.githubusercontent.com/54889301/223208924-3e7b9ba2-446b-4b53-8b8f-ada1db748cc7.png)

Thanks

**Comment by zizusoft** [comment]
Hi @dotMorten,

I've just noticed that this looks like the same issue as #96 ?

**Comment by droll2571** [comment]
@zizusoft,

I was experiencing the same issue in my dotnet MAUI application until I set the window's persistence ID.

![image](https://user-images.githubusercontent.com/20326929/226508231-00b4436d-4050-4c0b-9a05-7c23584611fe.png)

**Comment by dotMorten** [comment]
That’s really odd. The persistence has nothing to do with auth
