### ISSUE TITLE
NU1605 Error

### ISSUE THREAD

**Issue by BlyZeYT** [dotMorten/WinUIEx#113]
Downgrade of the package "Microsoft.Windows.SDK.BuildTools" from 10.0.22621.1 to 10.0.22000.194 was found.

I'm using .NET MAUI on .NET6 and WinUIEx 2.1.0

I don't get this error fixed
Thx in advance for help :)

**Comment by dotMorten** [comment]
Looks like you're referencing an out of date package, and another package requires something newer. This would be an issue in your project.

**Comment by andreyrd** [comment]
The package conflict comes from MAUI itself.. and is still an issue with .NET 7.0.
It looks like WinUIEx is no longer compatible with .NET 7.0 / MAUI?

**Comment by dotMorten** [comment]
Winuiex is compatible with Maui but you need to tell your project to explicitly reference the newer winui (Maui defaults to 1.2 right now)
