### ISSUE TITLE
Support tabbed backdrop for Win11 22H2 and up

### ISSUE THREAD

**Issue by X1nto** [dotMorten/WinUIEx#114]
Windows 11 22H2 introduced new backdrop APIs which include the Tabbed backdrop type. 
The reference can be found [here](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwm_systembackdrop_type). 

This is basically the backdrop that the new tabbed Notepad uses:
![image](https://user-images.githubusercontent.com/48173186/226166023-f1740c50-9a92-47b3-8a02-c3e585a9aa20.png)

[An example implementation](https://github.com/dongle-the-gadget/SystemBackdropTypes/blob/master/SystemBackdropTypes/MainWindow.xaml.cs)

**Comment by X1nto** [comment]
Actually, I think setting Kind to BaseAlt has the same effect. The backdrop looks pretty similar:
![image](https://user-images.githubusercontent.com/48173186/226166291-d22a91b2-6666-4ecd-b8d8-ea50af87ee91.png)
```cs
Backdrop = new MicaSystemBackdrop
{
    Kind = Microsoft.UI.Composition.SystemBackdrops.MicaKind.BaseAlt
};
```

**Comment by dotMorten** [comment]
Closing. Also backdrop APIs in WinUIEx has been deprecated in favor of v1.3's built-in backdrop APIs
