### ISSUE TITLE
Bug: When using WindowsEx class, closed application crashes on launch when activated from notification.

### ISSUE THREAD

**Issue by nik9play** [dotMorten/WinUIEx#115]
If there is a `WindowEx` window in the project, the application that is not running crashes when the notification is clicked and also when the application is started with the argument `----AppNotificationActivated:`.

When Native Code Debugging is enabled it gets me there:
![изображение](https://user-images.githubusercontent.com/13693620/227712851-7137ed06-d624-4172-aa86-beaaf1541319.png)

Seems like `m_activatedEventArgs` and `m_waitHandleForArgs` are null.

Looks like the window object does not even have to be created for the bug to happen. This happens in packaged in unpackaged modes.

I'm also created issue in WinAppSDK repo (https://github.com/microsoft/WindowsAppSDK/issues/3535) before I knew about the `WindowEx` bug.

**Comment by nik9play** [comment]
I think I've found the problem. When `WebAuthenticator` is initialized, it gets activated arguments:

![изображение](https://user-images.githubusercontent.com/13693620/227715887-a57cb83e-c40c-4f77-9461-f050732fe39c.png)

However, as stated in the MSDN docs (https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/app-notifications/app-notifications-quickstart?tabs=cs#step-3-register-to-handle-an-app-notification), you cannot call `GetActivatedEventArgs()` before the AppNotificationManager is registered. If `OnAppCreation` is commented out in the `Init` method, everything works fine.

**Comment by dotMorten** [comment]
> You cannot call GetActivatedEventArgs() before the AppNotificationManager is registered.

According to https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.appinstance.getactivatedeventargs?view=winrt-22621 you can call it before even App.xaml gets called and samples shows it called in the main method:
> 
<img width="470" alt="image" src="https://user-images.githubusercontent.com/1378165/231824975-ca75dfac-990e-470c-87e7-ae1d35ad6e78.png">

I this the above statement only applies if you use app notifications.
