### ISSUE TITLE
Updating System Backdrop to New API

### ISSUE THREAD

**Issue by AathifMahir** [dotMorten/WinUIEx#119]
Updating System Backdrop to New API with WinAppSDK 1.3 instead of current implementation,

I guess, we need to upgrade the windows app SDK to v1.3 first before going with the system backdrop.

I would love to create a PR on this. @dotMorten can I move on this?

**Comment by dotMorten** [comment]
This work was already done. Just pending release

**Comment by AathifMahir** [comment]
> This work was already done. Just pending release

Sure, that's great to hear

**Comment by dotMorten** [comment]
To be clear i didn't update the apis. I deprecated them in favor of the new apis.

And sorry for the delay in releasing. My code signing cert expired and waiting for a new one.

**Comment by AathifMahir** [comment]
> To be clear i didn't update the apis. I deprecated them in favor of the new apis.
> 
> And sorry for the delay in releasing. My code signing cert expired and waiting for a new one. 

No worries 👍
