### ISSUE TITLE
WindowExtensions.cs, MoveAndResize()

### ISSUE THREAD

**Issue by vfib** [dotMorten/WinUIEx#122]
Hello together,
I would like to move my window without resizing it. 
> SetWindowPositionAndSize(IntPtr hwnd, double x, double y, double width, double height)

So I read the doc of the MoveAndResize in WindowExtensions.cs, which states that for keeping the actual size

> Width of the window in device independent pixels, or <c>null</c> if keeping the current size</param>
> Height of the window in device independent pixels, or <c>null</c> if keeping the current size</param>

I would have to set a non nullable double to null? Perhaps im just missing something but generally Im curious about this. There is a function named SetWindowSize to only set the size, but no function to only set the position. Is this related to DPI things?
When using SetWindowPos from user32 I can set SWP_NOSIZE, but here its kind of irritating for me.

**Comment by dotMorten** [comment]
Now available in v2.3 release
