### ISSUE TITLE
DataRow doesn't work with WinUI

### ISSUE THREAD

**Issue by ScottAtBarco** [dotMorten/WinUIEx#126]
This works:
`    [TestMethod]
    [DataRow(1, "message", true, 2.0)]
    public void TestMethod1(int i, string s, bool b, float f) { }`

And this appears to work:
`     [WinUITestMethod]
    [DataRow(null)]
    public void TestMethod2(object o) { }`

But this does not:
`     [WinUITestMethod]
    [DataRow("")]
    public void TestMethod3(string s) { }`

You can see many errors in the generated code for the expansion to DataRowAttribute, even if you provide a DisplayName without embedded quotation marks. The first parameter, {""}, is where things go wonky.

Is there a trick for getting parameterized WinUI tests to work?

**Comment by dotMorten** [comment]
The Test Tools are being deprecated as an official set of test tools for WinUI since they have quite a lot of issues and no clear path forward. I think the approach taken isn't quite right, and causing more problems than they need. Moving forward their only purpose is for testing WinUIEx itself.
