### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by jarno9981** [dotMorten/WinUIEx#130]
Using latest WinUiEx 2.2.0

      private void CoreTitleBar_LayoutMetricsChanged(CoreApplicationViewTitleBar sender, object args)
      {
          if (FlowDirection == FlowDirection.LeftToRight)
          {
              CustomDragRegion.MinWidth = sender.SystemOverlayRightInset;
            
          }
          else
          {
              CustomDragRegion.MinWidth = sender.SystemOverlayLeftInset;
           
          }

          // Ensure that the height of the custom regions are the same as the titlebar.
          CustomDragRegion.Height = VBtn.Height = sender.Height;
      }

how to do it with the winuiex window

**Comment by dotMorten** [comment]
How to do what? Please be more specific.
Is this a bug or feature request? (Please use the Discussions section for questions)

**Comment by jarno9981** [comment]
Okay Then I Will Use Discussions
