### ISSUE TITLE
Add overload to WindowEx to Create a WindowEx from Window

### ISSUE THREAD

**Issue by AathifMahir** [dotMorten/WinUIEx#136]
Having this makes to easier to cross create between native native WIndow and WindowEx

**Comment by AathifMahir** [comment]
The problem that i'm facing is, SplashScreen Completed Event is Exposing Window object instead of WindowEx, Since i'm using WindowEx as Primary Windows, There's no way to assign the Window Object that i'm getting from Splash Completed Event, Unless i'm missing something @dotMorten

**Comment by dotMorten** [comment]
You'll get the type back you passed to the splashscreen. It can be any Window type, including WindowEx. You'll just cast it back to WindowEx.

**Comment by dotMorten** [comment]
See the cast here: https://github.com/dotMorten/WinUIEx/blob/66aa5fa8fa4247d412702f64fc8d3179b35b3dff/src/WinUIExSample/App.xaml.cs#L49

**Comment by AathifMahir** [comment]
> See the cast here:
> 
> https://github.com/dotMorten/WinUIEx/blob/66aa5fa8fa4247d412702f64fc8d3179b35b3dff/src/WinUIExSample/App.xaml.cs#L49

I tried that too, Seems like issue is related to Activation Service in My Project, Never mind, I might need to have custom splash screen implementation to solve this
