### ISSUE TITLE
IsMinimizable and IsMaximizable only working together

### ISSUE THREAD

**Issue by byrialsen** [dotMorten/WinUIEx#142]
Running demo 'WinUIExSample' setting either `IsMinimizable` or `IsMaximizable` is not working. System icons/buttons are grayed but still clickable.

But setting both to false at the same time will hide the system icons/buttons.

**Comment by dotMorten** [comment]
Woah. I saw them grayed out but I never actually pressed them. Since this property just maps directly to Windows App SDK's AppWindow properties, it's a Windows App SDK problem. I'll do a little more testing, then log a bug over there.

**Comment by dotMorten** [comment]
@byrialsen Looks like is already a known WinAppSDK issue when using ExtendsIntoTitleBar. See; https://github.com/microsoft/WindowsAppSDK/issues/3465

**Comment by dotMorten** [comment]
Should be fixed in 1.4.3 so closing here.
