### ISSUE TITLE
[Question] Using last Backdrop update in MAUI

### ISSUE THREAD

**Issue by Slals** [dotMorten/WinUIEx#145]
Hi,

I got curious by the last update with transparent backdrop. I saw the doc for setting up WinUIEx with MAUI, which works nicely. But regarding the part for adding a Backdrop I'm quite lost. The doc here https://dotmorten.github.io/WinUIEx/concepts/CustomBackdrops.html is showing how to add backdrop using XAML and `<Window>` tag but I didn't manage to find a way to do it in my MAUI app. Anyone has an idea?

**Comment by dotMorten** [comment]
Did you see https://dotmorten.github.io/WinUIEx/concepts/Maui.html#perform-operations-when-windows-are-created

Note that MAUI usually sets a background color that'll block the backdrop

**Comment by dotMorten** [comment]
Also see sample https://github.com/dotMorten/WinUIEx/blob/7c01aecf13753c045a9f0569b3a2beb2135ec2f7/src/WinUIExMauiSample/MauiProgram.cs#L31
