### ISSUE TITLE
Debugging with WebAuthenticator

### ISSUE THREAD

**Issue by thepaleone** [dotMorten/WinUIEx#152]
When I try to debug (using VSCODE) my MAUI app on Windows with using The WinUIEx.WebAuthenticator I receive the following error. It does work fine if I publish the app and install the package, but that makes debugging very difficult. Is there something I need to do in order to have this work while debugging?

```
System.InvalidOperationException: The WebAuthenticator requires a packaged app with an AppxManifest
   at WinUIEx.WebAuthenticator.Authenticate(Uri authorizeUri, Uri callbackUri, CancellationToken cancellationToken)
```

**Comment by dotMorten** [comment]
Sounds like VSCode launches the app differently than Vs2022. As the error states running as packaged is a requirement for the web authenticator.

**Comment by thepaleone** [comment]
I see. After thinking it through a bit I can understand why it works that way. Thanks!
