### ISSUE TITLE
WindowMessageReceived - Missing Events?

### ISSUE THREAD

**Issue by Dealman** [dotMorten/WinUIEx#157]
Are there any extra steps we need to take in order for more messages to be intercepted via `WindowMessageReceived`? Specifically, I'm trying to create events for `WM_LBUTTONDOWN [0x0201]` and `WM_LBUTTONUP [0x0202]` so I know when a user has clicked inside a window.

Intended use-case is to create custom logic for moving a window around, instead of only the title bar being the valid area for moving a window.

It seems like only a few messages are broadcasted via this event?

**Comment by dotMorten** [comment]
No messages are being filtered by WinUIEx, but it is most likely caused by WinUI intercepting these messages, acting on them and not forwarding them up the chain. Can't you just use WinUI's events?
