### ISSUE TITLE
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

### ISSUE THREAD

**Issue by dfmacom** [dotMorten/WinUIEx#158]
With a new blank app project template created, changing the base class of MainWindow.cs to WindowEx as shown [in the WinUI concept github page](https://github.com/dotMorten/WinUIEx/blob/main/docs/concepts/WindowEx.md) results in an unhandled memory exception in the MainWindow constructor.

System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

![image](https://github.com/dotMorten/WinUIEx/assets/154556251/a489b92b-7a87-4bc4-a8ff-35f3739e1924)

Steps to reproduce:
1. Create new WinUI3 project with the blank project template. 
2. Change MainWindow.cs and MainWindow.xaml.cs as shown in the steps in the link above. 
3. Build and run

Note that this issue seems to remain even after changing the base class back to "Window". The project can still build but the unhandled exception pictured continues to occur. It seems that it corrupted the project or something.

**Comment by dfmacom** [comment]
Uhm so I actually repeated this process again and it didn't happen this time. I will leave it up just so it is seen as it did happen as described and that project still seems corrupted. Handle this issue as you see fit

**Comment by dotMorten** [comment]
Did you change the type both in xaml and code behind ?

**Comment by dfmacom** [comment]
> Did you change the type both in xaml and code behind ?

Yes

**Comment by dotMorten** [comment]
So you don’t have a consistent repro any longer or does the original project still exhibit this behavior?
TBH sounds like the typical weird WinUI random instability and not a WinUIEx specific issue.

**Comment by dfmacom** [comment]
I do have the original project and it is still exhibiting the behavior that throws the exception. I can upload it as a public repo and link you to it in a bit, I need to clean some proprietary stuff out of it.

I would not be surprised if it is what you described as some of the WinUI random instability, though. There seems to still be plenty of that. Hopefully it will continue to be improved by the WinUI team

**Comment by dotMorten** [comment]
Close VS and delete bin and obj folders. Then open it again and see if it repros. My guess is some cache value from before you changing it wreaking havoc

**Comment by dfmacom** [comment]
I did that a few times among other things before opening the issue. 

Also, do the WinUIEX.TestTools and WinUIEX.TestTools.MsTest have .NET8 support?

**Comment by dotMorten** [comment]
@dfmacom I'm no longer maintaining the test tools and will be removed at some point, but there's nothing in there that prevents it from being used by a newer targetframework.

**Comment by dotMorten** [comment]
@TomPMoleman Thank you. Closing this issue since it's external.
