### ISSUE TITLE
Windows Maui app - WebAuthenticator for OIDC: activatedEventArgs.Kind is always Launch

### ISSUE THREAD

**Issue by rmaddu** [dotMorten/WinUIEx#176]
Hi,
To resolve a bug in the Windows App SDK for OIDC in my Windows Maui app (Could not find file ..AppxManifest.xml), we are trying to integrate the fix provided in https://dotmorten.github.io/WinUIEx/concepts/WebAuthenticator.html
https://dotmorten.github.io/WinUIEx/concepts/Maui.html#use-winuiexs-webauthenticator-instead-of-net-mauis

I have written code in **App.xaml.cs**: -
public partial class App : MauiWinUIApplication
{    
    public App()
    {
        if (WinUIEx.WebAuthenticator.CheckOAuthRedirectionActivation())
           return;
        this.InitializeComponent();        
    }
  
call is triggering to CheckOAuthRedirectionActivation and checking activatedEventArgs.Kind whether it is a Protocol or not?
My case always coming as **Launch** and returning False.

Also I have written below lines in identity service- 
WebAuthenticatorResult authResult = await WinUIEx.WebAuthenticator.AuthenticateAsync(authUri, callbackuri);

I am gettng login page and able to enter credentials. But it is not returning. And in **WebAuthenticator->Authenticate** code, not getting the response from below line
var uri = await tcs.Task.ConfigureAwait(false);

In manifest I have added -

<Extensions>
    <uap:Extension Category="windows.protocol">
        <uap:Protocol Name="test">
            <uap:DisplayName>$placeholder$</uap:DisplayName>
        </uap:Protocol>
    </uap:Extension>        
</Extensions>

callbackuri is - {test://callback/}

**Problem:** 

I am suspecting issue because of not getting the protocol kind, further call back is not registered initially, hence login page is not calling the call back function.

How to resolve this issue?

**Comment by dotMorten** [comment]
@rmaddu did you also make the required changes to the windows app manifest?

**Comment by rmaddu** [comment]
Yes. In ...\Platforms\Windows\Package.appxmanifest file I have added below lines. 
I didn't add any in ...\Platforms\Windows\app.manifest.. 

<Extensions>
    <uap:Extension Category="windows.protocol">
        <uap:Protocol Name="test">
            <uap:DisplayName>$placeholder$</uap:DisplayName>
        </uap:Protocol>
    </uap:Extension>        
</Extensions>

**Comment by rmaddu** [comment]
Anything missing here. Why kind is **Launch** always and why login window is not calling the call back function?

Any help to resolve this?

**Comment by dotMorten** [comment]
Hard to know. There's not a lot of info or a reproducer. Did you try debug into winuiex and see why? Does the Maui sample app work for you?

**Comment by rmaddu** [comment]
![1](https://github.com/dotMorten/WinUIEx/assets/52063294/499a65e5-f945-4183-8e06-bfb8d6fa58e5)
![2](https://github.com/dotMorten/WinUIEx/assets/52063294/d63cd1b7-ac3c-4f0f-876c-5f8ad10ef475)

sample snapshots added.
Getting Launch always.

**Comment by dotMorten** [comment]
One place says "test" and the other "myscheme".

Did you try the sample app that's in this repo? If that works try and reconfigure the app to work with your service and try again. 
Without a full reproducer app from you there's not much else I can offer than guesswork. The samples are there for you too to help debug.

**Comment by rmaddu** [comment]
ok.

**Comment by rmaddu** [comment]
Which sample should I execute - WinUIExMauiSample or WinUIExSample?

**Comment by rmaddu** [comment]
Hi, I am able to debug the WinUIExSample. Workflow also success.

I have integrated the code to my application -
- copied the WebAuthenticator.cs
- Package.appxmanifest: added below lines
  `<Extensions>
    <uap:Extension Category="windows.protocol">
        <uap:Protocol Name="hsi.nwm"/>
    </uap:Extension>
</Extensions>`

- in App.xaml.cs
`public App()
{
    if (WebAuthenticator.CheckOAuthRedirectionActivation())
        return;            
    this.InitializeComponent();           
}`

- in service code:
   `var authResult = await WebAuthenticator.AuthenticateAsync(authUri, callbackuri);`
   
   When I debug, I am getting login page. After successful login, asking to switch to app (see snapshot). But code in not hitting.
   
   
![1](https://github.com/dotMorten/WinUIEx/assets/52063294/7f18ebc1-9d89-4f06-beab-7d0ab3f1b14f)

   **any missing things here -**

**Comment by rmaddu** [comment]
Any help is appreciated...

**Comment by dotMorten** [comment]
Please provide a sample app that reproduces the problem. I can't guess what you're missing.
However since the sample app is working you're probably just missing something in your app or a setting is wrong.

**Comment by rmaddu** [comment]
![4](https://github.com/dotMorten/WinUIEx/assets/52063294/0d678c6b-01c7-46a7-9652-ac933a03f0a9)
![5](https://github.com/dotMorten/WinUIEx/assets/52063294/73ff584a-be50-4080-9571-5572fa55176e)
![3](https://github.com/dotMorten/WinUIEx/assets/52063294/a53e5c68-f3f5-4229-bc32-c30963476471)**

Instead of using WinUiEx, copied the WebAuthenticator.cs to project. **
Do we need to copy this to any specific location in project or anywhere is fine?
Do we need to copy any other files?

**Also provide any links or threads so that I can cross check once again.**
As we have integrated the code in product, I can't share it.

do we need to update any in below -

`[Activity(Label = "HxGN NetWorks Core Mobile", Theme = "@style/Maui.SplashTheme",
    ResizeableActivity = true,
    Exported = true,
    ScreenOrientation = ScreenOrientation.User,
    ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation | ConfigChanges.ScreenLayout | ConfigChanges.ScreenSize | ConfigChanges.SmallestScreenSize,
    LaunchMode = LaunchMode.SingleTask,
    WindowSoftInputMode = SoftInput.AdjustResize)]
[IntentFilter(new[] { Android.Content.Intent.ActionView },
    Categories = new[] { Android.Content.Intent.ActionView, Android.Content.Intent.CategoryDefault, Android.Content.Intent.CategoryBrowsable },
    DataScheme = "hxgnsi.nwcm")]
//[Activity(Theme = "@style/Maui.SplashTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation | ConfigChanges.UiMode | ConfigChanges.ScreenLayout | ConfigChanges.SmallestScreenSize | ConfigChanges.Density)]
public class MainActivity : MauiAppCompatActivity
{
    private ILogger<MainActivity> _logger;`
...
...

**Comment by rmaddu** [comment]
Please let me know if any other information is required?

**Comment by rmaddu** [comment]
One observation:
**In WinUIEx sample:** both redirect_uri and callbackUri is same.
          string callbackUri = "winuiex://";
         string authorizeUri = $"{server.Url}?response_type={responseType}&client_id={clientId}&redirect_uri= {Uri.EscapeDataString(callbackUri)}&scope=photo+offline_access";

var result = await WebAuthenticator.AuthenticateAsync(new Uri(authorizeUri), new Uri(callbackUri), oauthCancellationSource.Token);

In my sample: both redirect uri and callbackUri are different. redirect_uri is HTTPS URL.
string callbackUri = "hsi.nwm://callback/";     
redirect_uri = https://XX.com/XXAuthenticatorService/signin-oidc      

**How to handle this situation?**

**Is it possible to use a custom protocol in the Package.appxmanifest?**

**Comment by rmaddu** [comment]
When I integrated my authurl (https://XX.com/XXAuthenticatorService/mobileauth/OpenIdConnect) in WinUIEx sample application,  I am getting login page. After successful login, asking to switch to app. But app code is not hitting.

Seems redirecturi (i.e., HTTPS) and callbackuri ("winuiex://") are different, applications are not working.

Any help to resolve this?

**Comment by rmaddu** [comment]
Any help is appreciated...

**Comment by dotMorten** [comment]
The redirect url needs to use the same schema as what's in the app manifest and must be unique. You set that up in the service where you configure your app for oauth where you should also specify that schema.

**Comment by rmaddu** [comment]
already specified (ServiceConfig.ini) -
`WebAuthenticator:CallbackScheme=hsi.nwm://callback`

Package.appxmanifest: added below lines
`<Extensions> <uap:Extension Category="windows.protocol"> <uap:Protocol Name="hsi.nwm"/> </uap:Extension> </Extensions>`

in service code:
```
string authUrl = "https://XX.com/XXService/mobileauth/OpenIdConnect"
Uri authUri = new Uri(authUrl);
Uri callbackuri = new Uri("hsi.nwm://callback/");
var authResult = await WebAuthenticator.AuthenticateAsync(authUri, callbackuri);
```

Getting below dialog, but not hitting app -
![image](https://github.com/dotMorten/WinUIEx/assets/52063294/82814f32-a4e2-4769-b1d6-2a54cf1d3c35)


Any missing thing here?

**Comment by rmaddu** [comment]
Any help is appreciated...

**Comment by dotMorten** [comment]
Asking over and over again for a response isn't helping. This is FREE software that I develop in my spare time. Please don't keep pinging me for updates over and over again and expect immediate responses for something I'm doing on the side for free without any expectation of pay.
I've given you lots of hints and yet you still haven't provided the full sample that reproduces your issue like I asked.  My time is limited so please provide something where I don't have to spent time to try and reproduce something with some unknown servixe.
LOTS of people use this library so it's most likely a user error and not a bug so please refer to documentation and how oauth and app activation works first.
