### ISSUE TITLE
WinUIExMauiSample error

### ISSUE THREAD

**Issue by ndinesh231** [dotMorten/WinUIEx#177]
I have downloaded the sample application and ran (Using VS2022) WinUIExMauiSample application with "Perform oauth signing" and getting below error in the browser.
![image](https://github.com/dotMorten/WinUIEx/assets/64011743/71364544-339f-4cdb-bcb4-380d3ccf8be4)

Any idea what can be done ?

**Comment by dotMorten** [comment]
What browser are you using? This is how all browsers would redirect back to the app

**Comment by ndinesh231** [comment]
Using chrome browser.

**Comment by dotMorten** [comment]
Must be a setting in your browser preventing app redirect
