### ISSUE TITLE
Unable to build with ios and android target frameworks

### ISSUE THREAD

**Issue by ndinesh231** [dotMorten/WinUIEx#180]
Hello,

We are using WinUIEx in MAUI project and able to achieve functionality on windows platform. Recently we added iOS and android target frameworks and getting below error when we build.

**Error	NU1202	Package WinUIEx 2.3.4 is not compatible with net8.0-android34.0 (.NETCoreApp,Version=v8.0) / ios-arm64. Package WinUIEx 2.3.4 supports: net6.0-windows10.0.18362 (.NETCoreApp,Version=v6.0)**

How to solve this issue ? Should we do conditional implementation or is there any way to build the project ?

Thanks,
Dinesh

**Comment by dotMorten** [comment]
Please see MAUI documentation covering this
https://dotmorten.github.io/WinUIEx/concepts/Maui.html
