### ISSUE TITLE
Feature: Set allowMarshaling = false for CsWin32 to be compatible with NativeAOT

### ISSUE THREAD

**Issue by 0x5bfa** [dotMorten/WinUIEx#181]
## Summary

CsWin32 has an option to emit marshaling codes, which isn't compatible with NativeAOT. I'd like WinUIEx to be compatible with NativeAOT as WinAppSdk 1.6 coming.

NativeMethods.json
```json
{
    "$schema": "https://aka.ms/CsWin32.schema.json",
    "allowMarshaling": false,
    "public": true
}
```

With this change, some other lines of code would need to be changed because you can't use delegate directly.

```c#
namespace Windows.Win32.UI.WindowsAndMessaging;

[UnmanagedFunctionPointer(CallingConvention.Winapi)]
public delegate LRESULT WNDPROC(HWND hWnd, uint msg, WPARAM wParam, LPARAM lParam);
```
```c#
namespace WinUIEx;

var pWindProc = Marshal.GetFunctionPointerForDelegate(_oldWndProc);
var pfnWndProc = (delegate* unmanaged[Stdcall]<HWND, uint, WPARAM, LPARAM, LRESULT>)pWindProc;

return PInvoke.CallWindowProc(pfnWndProc, param0, param1, param2, param3);
```

**Comment by yaira2** [comment]
@dotMorten are there plans for WinUIEx to support NativeAOT?

**Comment by dotMorten** [comment]
While I haven't verified the above issue, I've been using it with NativeAoT and I'm not aware of any NativeAoT issues except the new TitleBar hitting this issue: https://github.com/microsoft/microsoft-ui-xaml/issues/9980

**Comment by dotMorten** [comment]
v2.4.1 should be AoT compatible.

**Comment by yaira2** [comment]
Thanks
