### ISSUE TITLE
The hidden taskbar icon is invalid after restarting explorer

### ISSUE THREAD

**Issue by ChenYiLins** [dotMorten/WinUIEx#185]
I hide the taskbar icon, when explorer was be restarted, the hidden taskbar icon will reappear.

This is code: `App.MainWindow.IsShownInSwitchers = false;`

And at the same time, I tried to get the value of IsShownInSwitchers. Even though the taskbar icon has appeared, the value of IshownInSwitchers is still false.

I guess the problem is that the properties of the program were reset when explorer was restarted.

Windows: Win11-x64-22631.4169
WinUIEx: 2.4.1
Windows App SDK: 1.6.240829007

**Comment by dotMorten** [comment]
This is just mapping to [AppWindow's `IsShownInSwitchers` property](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.windowing.appwindow.isshowninswitchers?view=windows-app-sdk-1.5) that you can access directly from Window.AppWindow.IsShownInSwitchers. I would encourage you to log an issue in the [Windows App SDK repo](https://github.com/microsoft/WindowsAppSDK) instead.
