### ISSUE TITLE
Getting "MSB3030	Could not copy the file ..winuiex\2.4.1\lib\net6.0-windows10.0.19041\WinUIEx\runtimes\win-x64\native\WebView2Loader.dll" because it was not found.

### ISSUE THREAD

**Issue by MagnusJohansson** [dotMorten/WinUIEx#188]
After adding WinUIEx to an OOB WinUI3 app template project, I get:
```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	MSB3030	Could not copy the file "E:\packages\NuGet\cache\winuiex\2.4.1\lib\net6.0-windows10.0.19041\WinUIEx\runtimes\win-arm64\native\WebView2Loader.dll" because it was not found.	App1WithWinUIEx	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5321		
```
<img width="808" alt="image" src="https://github.com/user-attachments/assets/2a434185-8ca0-46d3-959f-3125cca5c8f1">

Reproducible projects:

1. Project straight from VS Template:
https://github.com/MagnusJohansson/App1WithWinUIEx

Which gives me:
```
This version of the Windows App SDK requires Microsoft.Windows.SDK.NET.Ref 10.0.19041.38 or later.
    Please update to .NET SDK 6.0.134, 6.0.426, 8.0.109, 8.0.305 or 8.0.402 (or later).
    Or add a temporary Microsoft.Windows.SDK.NET.Ref reference which can be added with:
        <PropertyGroup>
            <WindowsSdkPackageVersion>10.0.19041.38</WindowsSdkPackageVersion>
        </PropertyGroup>
```
<img width="712" alt="image" src="https://github.com/user-attachments/assets/c6526320-2e05-4709-ac36-89d3624da351">

2. Project after adding the `WindowsSdkPackageVersion`:
https://github.com/MagnusJohansson/App1WithWinUIEx/tree/feature/amend-appsdk-requirements

All good.

3. Adding the latest WinUIEx Nuget package:
https://github.com/MagnusJohansson/App1WithWinUIEx/tree/add-winuiex

I now get the "WebView2Loader.dll" error as stated at the top.
<img width="808" alt="image" src="https://github.com/user-attachments/assets/70f838b3-1aca-4ff7-8357-5bd3f41d0ea8">

Of course, if I clone this WinUIEx repo and build, everything works, because then I have those runtime dependencies:
<img width="689" alt="image" src="https://github.com/user-attachments/assets/d8248b3f-4e05-494f-914a-089f45a5ecc0">

But I don't have them in my NuGet cache:
<img width="530" alt="image" src="https://github.com/user-attachments/assets/9aa6a92c-c104-4959-88bd-4602361cc69e">

Any ideas?

**Comment by Trix07** [comment]
I have the same issue, not only with the WinUIEx NuGet package but also with some internal NuGet packages. I think it has something to do with the decoupling of WebView2 from WinUI in the new 1.6 release, but so far I haven't found any workaround other than downgrading to 1.5.

**Comment by dotMorten** [comment]
Which version are you referencing? There’s a bug in webview package that 1.6 of windows app Sdk relies on but I added a workaround for that in 2.4.1.

If you are already on 2.4.1 could you share a repro app?

**Comment by MagnusJohansson** [comment]
@dotMorten sure, see the third link in my original post.

**Comment by dotMorten** [comment]
Actually I know what’s going on. I know I added that workaround for this issue but don’t see it now. Something in a merge must have gone wrong. I’ll get a fix out in a few hours …

**Comment by dotMorten** [comment]
I restored the fix but it'll be a little while before I can get to test it. If you have a minute, you can try the nuget package that'll be generated once the action completes here in a few minutes: https://github.com/dotMorten/WinUIEx/actions/runs/11035641248

**Comment by MagnusJohansson** [comment]
I downloaded the WinUIEx.2.4.2.nupkg file from the action artifacts and referenced it as a local Nuget feed.
Seems to compile now.

**Comment by dotMorten** [comment]
Thanks for confirming. Looks like this issue only affects projects with a separate packaging project, which is why I missed it. It's a non-issue with single-project packaged apps.

**Comment by dotMorten** [comment]
Fixed in v2.4.2

**Comment by dotMorten** [comment]
@MagnusJohansson and thanks for the donation too! I'm having an extra coffee today :)

**Comment by dotMorten** [comment]
Also see this in community toolkit: https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/216
