### ISSUE TITLE
Got Support for .net8, 9?

### ISSUE THREAD

**Issue by showtroylove** [dotMorten/WinUIEx#190]
The nuget package appears to support .net6.  Does this package support more recent versions of .net?

![dc8348ac2c0d60fa653b4074f63ac2a](https://github.com/user-attachments/assets/12f45925-7406-4c15-9c40-16553acc1ee7)

**Comment by dotMorten** [comment]
That merely indicates the minimum required version. That goes for any nuget package.

**Comment by showtroylove** [comment]
Hmmm, my visual studio 2022 (latest) appears to flag and complain about
that package.  Do I have the correct package?

**Comment by showtroylove** [comment]
error NETSDK1148: A referenced assembly was compiled using a newer version
of Microsoft.Windows.SDK.NET.dll. Please update to a newer .NET SDK in
order to reference this assembly.
2>Done building project "*.csproj" -- FAILED.

**Comment by dotMorten** [comment]
Are you referencing the latest winappsdk and did the required workaround to make that work until the next.net update? (See winappsdk release notes)
