### ISSUE TITLE
NuGet package missing net9.0-windows

### ISSUE THREAD

**Issue by fredl49** [dotMorten/WinUIEx#196]
Please update for net9.0.

**Comment by dotMorten** [comment]
@fredl49 Why? It works just fine as-is with .NET 9.

**Comment by fredl49** [comment]
I'm sure it works as I used it for the .net 9 previews but it doesn't  currently install for a .net9.0 project

**Comment by fredl49** [comment]
I was getting a package downgrade error, which has now disappeared. Sorry about that and many many thanks for your excellent work.
