### ISSUE TITLE
Package WinUIEx 2.5.0 and  net8.0 (.NETCoreApp,Version=v8.0) are not compatible

### ISSUE THREAD

**Issue by infofromca** [dotMorten/WinUIEx#198]
包 WinUIEx 2.5.0 与 net8.0 (.NETCoreApp,Version=v8.0) 不兼容。 Package WinUIEx 2.5.0 support : net6.0-windows10.0.19041 (.NETCoreApp,Version=v6.0)
This version of the Windows App SDK requires Microsoft.Windows.SDK.NET.Ref  or later.
    Please update to .NET SDK 6.0.134, 6.0.426, 8.0.109, 8.0.305 or 8.0.402 (or later).
    Or add a temporary Microsoft.Windows.SDK.NET.Ref reference which can be added with:
```
       ```
 <PropertyGroup>
            <WindowsSdkPackageVersion></WindowsSdkPackageVersion>
        </PropertyGroup>
```
```

**Comment by dotMorten** [comment]
This is a .NET SDK bug that should go away with the latest SDK updates. You can add the following to work around it, as the error says:
`<WindowsSdkPackageVersion>10.0.19041.41</WindowsSdkPackageVersion>`
