### ISSUE TITLE
IsTitlebarVisible doesn't work in CompactMode

### ISSUE THREAD

**Issue by AlexanderBlackman** [dotMorten/WinUIEx#20]
Anyway, thank you for the great plugin, it really fixes all the annoying omissions in the new GUI framework.

**Comment by dotMorten** [comment]
Define "Doesn't work" (exception thrown, not showing etc?). The Compact presenter doesn't support changing titlebar visibility.

**Comment by AlexanderBlackman** [comment]
> 

Ah! Nevermind then, nothing crashed.  I see you are corrrect about the Compact Presenter not supporting tittlebar visibility changes.
