### ISSUE TITLE
Window size not correctly applied

### ISSUE THREAD

**Issue by char8t** [dotMorten/WinUIEx#200]
First big thumbs up for this library. It is a must have for any WinUI3 app!

I do not know if this is really an issue or if i am missing something here but when specifying the window size it is actually a little bit smaller then requested:

![image](https://github.com/user-attachments/assets/6aa52892-6a94-4cd1-abee-4fe1eef983d6)

Is this expected? If so why? Again this is not really an issue for me but i find it a bit odd.

**Comment by dotMorten** [comment]
I believe it is because of Windows taking the drop shadow into account as well. If so perhaps there’s a way to detect that and add to it but would take some research

**Comment by char8t** [comment]
Wow i did not expect such a fast response! I opened an issue at the WinUI3 repo as the same behavior can be observed when specifiying window dimensions via a call to `AppWindow.Resize(new SizeInt32(800, 450))`

https://github.com/microsoft/microsoft-ui-xaml/issues/10204

**Comment by char8t** [comment]
Closed as this is not a real bug. It just means that `ResizeClient` + `AppWindow.TitleBar.Height` should be used when using `ExtendContentIntoTitleBar = true`.

**Comment by Slion** [comment]
That's the title bar, it's the drop shadow.
Powertoys FancyZones is using the following function to take the size of the shadows into account when snapping windows to zones:
https://github.com/microsoft/PowerToys/blob/83817700e18164495413cfe8884a8edf40c55ad6/src/modules/fancyzones/FancyZonesLib/WindowUtils.cpp#L364

Basically they get the size of the window then get the size of the frame containing the window from the DWM using `DWMWA_EXTENDED_FRAME_BOUNDS` and compute the difference to workout the size of the shadows.
Funny enough that code assumes there is no shadow at the top of a window but only on the three other edges which is indeed the case on Windows 11.

**Comment by char8t** [comment]
@Slion So what would be the ultimate "fix" to have the window sized as requested taking everything into account? My initial issue was that requesting a window of a specific size was indeed sized differently (ie. smaller).

**Comment by Slion** [comment]
Well using the above method you can request a larger window size so that it is of the desired dimension.
