### ISSUE TITLE
[Question / Proposal] Is it possible to force the tray icon to show a tooltip?

### ISSUE THREAD

**Issue by zipgenius** [dotMorten/WinUIEx#23]
Is it possible to force the tray icon to show a tooltip?

**Comment by dotMorten** [comment]
As just display a text when you hover, or you want it to be interactive too?

**Comment by zipgenius** [comment]
Maybe just on hover for now. It would be enough for many cases,

**Comment by dotMorten** [comment]
It is now :-)

**Comment by zipgenius** [comment]
Thanks :)
