### ISSUE TITLE
[Question] Is there any chance to customize titlebar text foreground color?

### ISSUE THREAD

**Issue by zipgenius** [dotMorten/WinUIEx#24]
While it is possible to set the titlebar color, sometimes it may be useful to customize the foreground color in order to avoid, e.g. black text on dark background color.

**Comment by dotMorten** [comment]
Yes WinUI already provides this ability and WinUIEx doesn’t need to provide anything there. Look at the AppWindow class which has these settings (And WinUIEx gives you easy access to)
