### ISSUE TITLE
Controls in Custom Titlebar aren't interactive

### ISSUE THREAD

**Issue by AlexanderBlackman** [dotMorten/WinUIEx#27]
The custom titlebar works for textblocks/images, but not for interactive content.

![example of titlebar not being interactive](https://user-images.githubusercontent.com/51733876/154770174-59289177-9810-4040-8f7c-c33e3b231e1e.png)
None of the usercontrol buttons or textbox work or respond, but the titlebar is still dragable.

2nd Issue, if custom content is too wide, the   min/max/close buttons are covered up and unusable.
![Example of Image covering up titlebar buttons](https://user-images.githubusercontent.com/51733876/154772592-da06da93-8056-4408-acdc-975cb6bfe9b9.png)

Edit:  On further testing, controls are ONLY interactive if they have a min/max/close button behind them (eg, when the window is very narrow), but become unresponsive after window is widened.  Draggability is inconsistent, sometimes it works, sometimes it doesn't.
![the controls work](https://user-images.githubusercontent.com/51733876/154777150-47201389-fcf5-450d-8eb5-297c33b304e0.png)

**Comment by dotMorten** [comment]
I've decided to deprecate and ultimately remove the xaml titlebar APIs - use the Window.SetTitleBar( ... ) WinUIEx provides instead.
Wrt interactive content, there are some APIs for allowing this in the AppWindow class, but I've found them to be quite unpredictable an essentially unusable.

**Comment by AlexanderBlackman** [comment]
No worries, I guess that's to expected when the official sdk finally provides the formerly missing features WinUIEx filled in.
