### ISSUE TITLE
[Question] Is there any way to compose an AppWindow with a Frame in desktop app?

### ISSUE THREAD

**Issue by YesOhh** [dotMorten/WinUIEx#28]
WinUI3 1.0.0 Desktop c#

In UWP, I can use
`ElementCompositionPreview.SetAppWindowContent(appWindow, new Page());`
to set an AppWindow's content.
However, this function doesn't exist in the WinUI3.

How can I  compose an AppWindow with a Frame?

**Comment by dotMorten** [comment]
Frames goes in Windows, now AppWindows
