### ISSUE TITLE
Double click to Tray Icon exception

### ISSUE THREAD

**Issue by HavenDV** [dotMorten/WinUIEx#29]
<img width="783" alt="image" src="https://user-images.githubusercontent.com/3002068/155685837-35209a8d-e074-4333-997e-a55bf486549d.png">

Repro:
1. Click <img width="204" alt="image" src="https://user-images.githubusercontent.com/3002068/155686603-b0a13b3f-1295-4c9e-9bb8-fce9f0bd7dd1.png">
2. Double click Tray Icon
3. Repeat if no exception(race condition)

Although this is the Example side exception, it is worth taking care of users who copy this.

**Comment by dotMorten** [comment]
I've decided to deprecate and ultimately remove the trayicon APIs as they are still lacking lots of features to be truly functional, and have various lifecycle issues. I'm just not happy with where they are at, but might bring the back in the future.
