### ISSUE TITLE
TrayIcon Dispose exception after Toggle

### ISSUE THREAD

**Issue by HavenDV** [dotMorten/WinUIEx#30]
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/3002068/155686046-b6af0a65-06b5-4929-98a0-868592b1f2dd.png">

Repro: 
1. Click <img width="216" alt="image" src="https://user-images.githubusercontent.com/3002068/155686144-1e7e6b2d-bb1d-462e-9956-e934132518fa.png">
2. Click <img width="226" alt="image" src="https://user-images.githubusercontent.com/3002068/155686166-465fdc15-fff7-426f-9a39-4db6fc9a57a4.png">

**Comment by dotMorten** [comment]
I haven't been able to reproduce this. Could you share the full stack trace as well?

**Comment by HavenDV** [comment]
This does not always appear. Sometimes this happens if you then click on the tray icon.
<img width="1485" alt="image" src="https://user-images.githubusercontent.com/3002068/155818846-b864b310-29b5-4efe-82bd-878094420ac3.png">

<img width="347" alt="image" src="https://user-images.githubusercontent.com/3002068/155818913-c39908c1-08d9-493d-99b8-f660d04c2a7c.png">

**Comment by Tide** [comment]
I can confirm this as well.  To reproduce it you have to do a fresh start of the solution.  If you have run debug on the solution and closed the app at least one time this error will not happen.  

Start the solution.
Start debug.
Click "Toggle Tray Icon". (Icon shows in tray)
Click "Toggle Tray Icon". (Error show above occurs)

**Comment by dotMorten** [comment]
I've decided to deprecate and ultimately remove the trayicon APIs as they are still lacking lots of features to be truly functional, and have various lifecycle issues. I'm just not happy with where they are at, but might bring the back in the future.
