### ISSUE TITLE
Is ShowInTaskbar = false Possible?

### ISSUE THREAD

**Issue by Tide** [dotMorten/WinUIEx#31]
Is adding in a ShowInTaskbar property like the one in WPF possible?  I see in your demo that the taskbar icon goes away when minimizing to tray.  This is perfect for my application.  The only part I need to add is to have it not show the taskbar icon when the window is showing.  

Thanks,
Tide

**Comment by dotMorten** [comment]
Yes it’s possible. In fact it’s what the minimize to tray button does

**Comment by Tide** [comment]
I see that minimize to tray is calling Hide().  I want to show the window but not the taskbar icon.  I found this post [https://github.com/dotMorten/WinUIEx/discussions/url](url) descrbing a way to do it but I have had no luck so far.

**Comment by Tide** [comment]
After learning more about WinUI3 and other things I figured out "IsShownInSwitchers" is the same as "ShowInTaskbar" was before.  That combined with your library does what I am looking for.  

Thanks for your work on this.
