### ISSUE TITLE
InvalidCastException in DynamicInterfaceCastableHelpers

### ISSUE THREAD

**Issue by terrycox** [dotMorten/WinUIEx#34]
An exception is thrown if casting WindowEx to Window, as shown in the WinUIExSample app.
![image](https://user-images.githubusercontent.com/1378165/157105780-bf99d472-cb44-49ce-a7f6-f6f16b8f13ed.png)

![image](https://user-images.githubusercontent.com/1378165/157105817-1017a638-752d-4c9c-a469-3b48996867fc.png)

Repro: [WinUIExZIssue.zip](https://github.com/dotMorten/WinUIEx/files/8200351/WinUIExZIssue.zip)

**Comment by dotMorten** [comment]
Ran the sample and it ran fine.

Do you see this issue with a blank project that you didn't change to `WindowEx`?
If so, do you have the correct tooling installed to be able to run as a single-project packaged app? (try the two-project one with a separate packing project as that generally causes fewer problems).

**Comment by dotMorten** [comment]
One more thing, you say "An exception is thrown if casting WindowEx to Window", but I don't see a cast anywhere.

**Comment by terrycox** [comment]
Sorry, I tried it with and without the cast. No joy either way.
If it's not in your code, then it's in our setup, and we'll try repackaging.
Thanks for looking at it.
BTW, your sample contains the cast to Window.
