### ISSUE TITLE
[Proposal] Use WinRT Component instead of C# class library

### ISSUE THREAD

**Issue by dongle-the-gadget** [dotMorten/WinUIEx#36]
Currently WinUIEx is a C# class library, meaning that it can only be consumed by .NET WinUI 3 applications. Would appreciate if you could move the library to become a WinRT Component, which allows all WinUI 3 applications to consume the library.

**Comment by dotMorten** [comment]
Thank you for the suggestion but making it a WinRT component has major drawbacks and limitations so not something I am planning to do. The change would be quite bad for people who are using this with .NET

**Comment by chingucoding** [comment]
@dotMorten am I right in with the assumption that supporting C++ (or even implementing this in C++/WinRT) is not a plan of yours then?
