### ISSUE TITLE
Using WebAuthenticator on Google shows "response_type is missing" error

### ISSUE THREAD

**Issue by felinepunch** [dotMorten/WinUIEx#39]
Using WebAuthenticator on Google shows "response_type is missing" error.

My codes is shown below.

```
const string authorizationURI = "https://accounts.google.com/o/oauth2/v2/auth";
const string callBackURI = "xxxxxx://loggedin";
WebAuthenticatorResult result = await WinUIEx.WebAuthenticator.AuthenticateAsync(new Uri(authorizationURI), new Uri(callBackURI));
```
Error message in web browser(MS Edge version 101.0.1210.32 64 bit)

> Authorization Error
> Error 400: invalid_request
> Required parameter is missing: response_type

**Comment by dotMorten** [comment]
Your `authorizationURI` appears to missing a bunch of parameters.
