### ISSUE TITLE
Window Transparency

### ISSUE THREAD

**Issue by Samuel12321** [dotMorten/WinUIEx#42]
Thanks for creating this incredibly useful project

A really useful feature missing from WinUI 3 is window background transparency. It would be very useful if you could add support for this.
Perhaps similar to Backdrop.Mica & Backdrop.Acrylic   --> Backdrop.Transparent
  

While not officially supported someone has managed to do it [here](https://github.com/microsoft/microsoft-ui-xaml/issues/1247#issuecomment-1093303460), however it is ridiculously over complicated.
Official support tracked on [Productboard](https://portal.productboard.com/winappsdk/1-windows-app-sdk/c/44-transparent-window-backgrounds) and [Github](https://github.com/microsoft/microsoft-ui-xaml/issues/1247) but i doubt it will occur any time soon.

**Comment by dotMorten** [comment]
Mica and Acrylic is already there but you need to compile the library with the latest preview. Once 1.1 of the windows app sdk ships this will have it too

**Comment by Samuel12321** [comment]
hi, thanks for the quick reply.
I think you may have misinterpreted my question, i was asking about **Transparency** not Mica and Acrylic

I'm already using Backdrop.Mica, its quite useful.

**Comment by dotMorten** [comment]
Matching WinUI issue: https://github.com/microsoft/microsoft-ui-xaml/issues/1247

**Comment by dotMorten** [comment]
See https://github.com/cnbluefire/WinUI3TransparentBackground for an example of a transparent background.

**Comment by dotMorten** [comment]
Example / use case by @niels9001

https://github.com/dotMorten/WinUIEx/assets/1378165/0e56dc12-6e76-4725-9066-8b05ce935f74

**Comment by dotMorten** [comment]
Making some progress, and decided to abuse it :-)
https://github.com/dotMorten/WinUIEx/assets/1378165/7c41727f-3a33-459e-bbce-82c65c4d603c

**Comment by dotMorten** [comment]
Snapshot of @niels9001's design with this new API:
![image](https://github.com/dotMorten/WinUIEx/assets/1378165/95fdc3d3-a7d7-4fb4-8f66-3695e6bc082e)

**Comment by niels9001** [comment]
> Snapshot of @niels9001's design with this new API:
> ![image](https://github.com/dotMorten/WinUIEx/assets/1378165/95fdc3d3-a7d7-4fb4-8f66-3695e6bc082e)
> 

That's amazing 😁😁🚀🚀!

I was wondering - do acrylic brushes work with this as well?

**Comment by dotMorten** [comment]
Yeah it's not as blurred as I had hoped

**Comment by dotMorten** [comment]
Now available in v2.3 release
