### ISSUE TITLE
We are getting error after updating WinUIEx package 1.1.0  to 1.4.3

### ISSUE THREAD

**Issue by VikasSaxenaxcdify** [dotMorten/WinUIEx#49]
Error description

Assembly 'WinUIEx' with identity 'WinUIEx, Version=1.4.3.0, Culture=neutral, 
PublicKeyToken=null' uses 'WinRT.Runtime, Version=1.6.0.0, Culture=neutral,
 PublicKeyToken=99ea127f02d97709' which has a higher version than referenced assembly 'WinRT.Runtime' with identity 'WinRT.Runtime, Version=1.5.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709'

**Comment by dotMorten** [comment]
Which version of .NET and Visual Studio do you have? Are you on latest? The latest WinUI requires a newer .NET runtime (6.0.4+ I believe)

**Comment by dotMorten** [comment]
Closing for now as I don't believe this is related to WinUIEx. Feel free to reopen with the extra information if you believe this is WinUIEx causing this.
