### ISSUE TITLE
Backdrop opacity/brush adjustment

### ISSUE THREAD

**Issue by rocksdanister** [dotMorten/WinUIEx#50]
Is it possible to add the option to adjust the opacity/transparency level or brush of the backdrop?

It is hard to read texts with acrylic:
![Screenshot 2022-06-06 102008](https://user-images.githubusercontent.com/17554161/172209765-eeeaca52-073a-4de2-ade3-9fe30a1fac3e.jpg)

Mica is too subtle:
![Screenshot 2022-06-06 104310](https://user-images.githubusercontent.com/17554161/172210069-43fcc325-7c43-460e-864a-5c91db6783fc.jpg)

**Comment by dotMorten** [comment]
No Acrylic is just whatever Microsoft defined it as is. What I usually do is I put a background in with a bit of transparency to tone it down.

**Comment by dotMorten** [comment]
Actually I'm wrong... Somehow overlooked the properties to control color and opacity 🤦 
I'll get that added...
