### ISSUE TITLE
Backdrop stops working after window is hidden using Closed event

### ISSUE THREAD

**Issue by rocksdanister** [dotMorten/WinUIEx#55]
**Bug:**
Mica/Acrylic backdrop stops working when Window is hidden then shown again using Closed event.

**Use case:**
Application runs UI as a separate WinUI program and has the option to hide the program instead of closing when not in use.

**Example to reproduce:**
```csharp
//Closed is closing. 
//ref: https://github.com/microsoft/microsoft-ui-xaml/issues/5454
this.Closed += (s, e) =>
{
    e.Handled = true;
    this.Hide();
};
...
await Task.Delay(2000);
this.Close();
await Task.Delay(2000);
this.Show(); //no backdrop.
```

```csharp
await Task.Delay(2000);
this.Hide();
await Task.Delay(2000);
this.Show(); //backdrop 
```

**Comment by dotMorten** [comment]
@rocksdanister Thank you for the great error report. I pushed a fix.
I'm overhauling the backdrop API quite a lot though to give you more control, and the fix will be in the new API.
For now, try setting the backdrop to default and back again to "restore" it right before calling Show.

**Comment by JasonWei512** [comment]
@dotMorten 
I have the exact same problem in v1.8.0.
To workaround this bug I have to set `Window.Backdrop` to `new MicaSystemBackdrop()` after calling `Show()`.

**Comment by dotMorten** [comment]
@JasonWei512 Could you provide a repro? The above repro was used to verify the fix.

**Comment by JasonWei512** [comment]
Reproduction:
https://github.com/JasonWei512/WinUIExMicaBackdropBug
