### ISSUE TITLE
Please provide option to add additional icons buttons to task bar 

### ISSUE THREAD

**Issue by jindal1979** [dotMorten/WinUIEx#59]
Dear Morten,

I am using your library in my project and it is of great help. It would be good to add a feature where you can add additional icons to task bar like Change Theme, User Feedback, etc. (Similar to Visual Studio Installer Screen).

Let me know your thoughts. If you need help, I am willing to support it in WinUIEx.

-Munish

**Comment by dotMorten** [comment]
I'm not quite following. Could you provide some examples?

**Comment by jindal1979** [comment]
![Screenshot 2022-06-29 192044](https://user-images.githubusercontent.com/22019325/176453382-90fca474-e330-40ee-a32b-8e67568cc2eb.png)

Please see the attached Visual Studio Installer screenshot. There are 5 buttons on Task Bar :
Theme Change Button,
Feedback Button,
Minimize Button,
Maximize Button and
Close Button

If there is a way to add the Theme Change Button or Feedback Button in addition to 3 usual buttons (Minimize, Maximize, Close), it will be helpful to add addition functionality.

**Comment by dotMorten** [comment]
You can already do this with WinUI 3 today by extending your UI into the titlebar. There's not really anything for WinUIEx to do here.
