### ISSUE TITLE
Extension to Add the min height and width

### ISSUE THREAD

**Issue by MarkBQE** [dotMorten/WinUIEx#6]
Extension to control min height and width will be a good one to add. 

https://github.com/microsoft/microsoft-ui-xaml/issues/2945

**Comment by fourdragons** [comment]
Apologies for the somewhat off-topic comment, but I just had to say THANK YOU! Both to dotMorten (for doing this), and to MarkBQE for mentioning the issue that brought me here! Now, if only I had discovered this say, oh, two days ago! I just spent the last two days (duplicating?) some of your work here. Nice to see I'm not the only one that thinks WinUI 3 is missing just a few things right now.

**Comment by dotMorten** [comment]
@fourdragons Thank you for the kind words. Much appreciated.

**Comment by dotMorten** [comment]
For reference UWP equivalent: https://docs.microsoft.com/en-us/uwp/api/windows.ui.windowmanagement.preview.windowmanagementpreview.setpreferredminsize?view=winrt-22000#Windows_UI_WindowManagement_Preview_WindowManagementPreview_SetPreferredMinSize_Windows_UI_WindowManagement_AppWindow_Windows_Foundation_Size_

Looks like being able to do this requires listening for WM Messages and inspecting https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-minmaxinfo

**Comment by dotMorten** [comment]
The `WindowEx` class now has `MinWidth` and `MinHeight` properties, If you don't want to use the custom window class, you can use the new message monitor to do the same thing `WindowEx` is doing: https://github.com/dotMorten/WinUIEx/blob/cd395e2c451df7eb431d4f522eadbe5e5e72f498/src/WinUIEx/WindowEx.cs#L66-L94

**Comment by IndianaGary** [comment]
Hi Morten,

 

Thank you for implementing this! It also raises a question: does WinUIEx
make it possible to determine which MONITOR a particular Window is on? Or is
this something I can straightforwardly implement myself. My Win32 is a bit
rusty ATM.

 

Regards,

Gary

**Comment by dotMorten** [comment]
Use this to get a list of Monitors: https://dotmorten.github.io/WinUIEx/api/WinUIEx.MonitorInfo.GetDisplayMonitors.html#WinUIEx_MonitorInfo_GetDisplayMonitors
Then use the `PositionChanged` event to determine what monitor the window intersects the most.

**Comment by IndianaGary** [comment]
Perfect! Thanks for the help!

Gary
