### ISSUE TITLE
Set default values for Mica fallback colors

### ISSUE THREAD

**Issue by mikebattista** [dotMorten/WinUIEx#65]
WinUI designers have said that `Background="{ThemeResource SolidBackgroundFillColorBaseBrush}"` is the recommended fallback background for when Mica isn't available. We should default the fallback colors in WinUIEx to the equivalent values so everyone gets the recommended fallback colors by default.

Looking at the definition for that resource in VS in Generic.xaml, the value for Dark is `0x202020` and Light is `0xF3F3F3`.

**Comment by dotMorten** [comment]
> WinUI designers have said that Background="{ThemeResource SolidBackgroundFillColorBaseBrush}" is the recommended fallback background for when Mica isn't available

There's no way for the Mica class to default to this, since it can't get the reference to the resource. You'll have to set this from app logic. Once/if https://github.com/microsoft/microsoft-ui-xaml/issues/7305 is fixed, you can just set it the same way with a `{ThemeResource}` value.

**Comment by mikebattista** [comment]
We know the hex values for the colors. Can't we set those in the library so all developers don't need to discover them and set them themselves?

**Comment by dotMorten** [comment]
We don't know the hex values - that is both system and app dependent, since that value could have been overwritten in application styles or system themes.

**Comment by mikebattista** [comment]
We'd like to ship a Template Studio update late July/early August. Do you think you'll have an updated release with this by then?

**Comment by dotMorten** [comment]
It’s already in this v1.8.0 release 😎

**Comment by mikebattista** [comment]
Awesome!
