### ISSUE TITLE
Setting the titlebar to collapse shows a white border

### ISSUE THREAD

**Issue by ArchieCoder** [dotMorten/WinUIEx#67]
1- Run the sample
2- Toggle the Is Titlebar Visible switch

Windows 11: 22H2 - 22621.169

![image](https://user-images.githubusercontent.com/1608424/178576123-5afbc573-2e72-4ab3-8eac-e056e318c809.png)

**Comment by dotMorten** [comment]
Closing, since this is an AppSDK bug. Link to bug above.

**Comment by rocksdanister** [comment]
Removing `WS_THICKFRAME` seems to do the trick:
https://github.com/rocksdanister/GlobalColorPicker

**Comment by dotMorten** [comment]
Should be fixed in Windows App SDK 1.4.3

**Comment by Jimbo99** [comment]
> Should be fixed in Windows App SDK 1.4.3

I've just read that thread https://github.com/microsoft/microsoft-ui-xaml/issues/8947. Many thanks for drawing their attention to that bug, @dotMorten. That thread comes across as almost a microcosm of developing in WinUI3 - so much pushback from MS sometimes over things we want to do with it and need to do in our particular projects. Like pushing water uphill sometimes lol. Anyway, really appreciate all your great work!
