### ISSUE TITLE
Remove Backdrop fallback workaround

### ISSUE THREAD

**Issue by dotMorten** [dotMorten/WinUIEx#70]
In 1.2, WinAppSDK is going to provide the fallback for background when mica/acrylic isn't supported: https://github.com/microsoft/WindowsAppSDK/issues/2637

This means WinUIEx can remove the workaround for that once 1.2 ships:
https://github.com/dotMorten/WinUIEx/blob/ce3b8d6d270b8124c4f16acc00b694fbc3d2dd9e/src/WinUIEx/WindowManager.Backdrop.cs#L73-L105

**Comment by rocksdanister** [comment]
>This means WinUIEx can remove the workaround for that once 1.2 ships:

Will you check the running WinAppSDK version the app is using.. what if its lower than 1.2?

**Comment by dotMorten** [comment]
> what if its lower than 1.2?

Once 1.2 ships WinUIEx will require 1.2

**Comment by dotMorten** [comment]
Completed in #e1a07a58dc06b648e3fc59dd2ebb7dd3f25c6fdf
