### ISSUE TITLE
Backdrop is not applied at all

### ISSUE THREAD

**Issue by EmrecanKaracayir** [dotMorten/WinUIEx#71]
Using Win11, WindowsAppSdk 1.1.3, WinUIEx 1.8.0, Windows 'Transparency effects' ON.

Am I doing something wrong?

I check for MainWindow's Backdrop in runtime and it is Mica like I wanted. But neither Mica nor Acryllic is applied to the window.

![image](https://user-images.githubusercontent.com/84916904/183247093-9c2a93b0-c80c-4e40-82dd-278e11492144.png)

**Comment by dotMorten** [comment]
Does your layout have a background defined? Make sure you don’t hide mica with your own background brushes

**Comment by EmrecanKaracayir** [comment]
Yes, I was being dumb for no reason. My page's layout's background was defined, that was the issue. Thank you for helping.
