### ISSUE TITLE
ElementTheme.Default not applied correctly on 1.8.0 (good with 1.7.0 and before)

### ISSUE THREAD

**Issue by TRadigk** [dotMorten/WinUIEx#72]
Hi DotMorten, 

I really appreciate your nuget package, it makes many things around windows a lot easier.

Today I tried V 1.8.0 and found an issue with ElementTheme Binding on a grid, which is not applied on children correctly. Please see the following collage of 6 screenshots. Only change is the version of you package:
![grafik](https://user-images.githubusercontent.com/92845708/183252328-7d3a0642-8afc-4568-9509-f0bae8bf778b.png)

from left to right you see theme "Light, Dark and Default" applied on the grid residing in the window.

Also I would like to use this issue to ask if you provide release notes somewhere?
And I also would like to know if you were able to hide the "close" button on windows on any presenter type?

**Comment by dotMorten** [comment]
Could you provide a simple sample that reproduces this? The ElementTheme property on Grid is part of WinUI so likely not WinUIEx causing it

**Comment by dotMorten** [comment]
Release notes are in the nuget package (which nuget.org will show)

**Comment by TRadigk** [comment]
Well.. I couldn't exactly repro the issue, but you can use the sample to see that the theme "default" is applied correctly without WindowEx, but theme is not changed with. Please let it in run with the debugger, since the actual set theme I've written to debug output.

https://github.com/TRadigk/ThemeBugSample

Code to use Mica is taken from Winui3 gallery.

**Comment by Bondarenko1990** [comment]
me too. ElementTheme.Default not applied correctly on 1.8.0 (good with 1.7.0 and before)
@dotMorten how to change the theme in the dialog box?
![image](https://user-images.githubusercontent.com/32612104/185054077-21d9ded8-713b-46e2-b686-f332866854aa.png)

**Comment by TRadigk** [comment]
@Bondarenko1990 the dialog should inherit the theme from its XamlRoot. Be suer to set any theme on the highest layer, if your design allows it. Thus typically you would do this on the window. If you design does not allow this, you have the "RequestedTheme" Property on the dialog, which you can bind to Viewmodel property if you want.

**Comment by Bondarenko1990** [comment]
@TRadigk thanks

**Comment by dotMorten** [comment]
Sorry this took so long. This has been fixed.
