### ISSUE TITLE
WindowManager.Get(this) crashes on start

### ISSUE THREAD

**Issue by PlonkaAdam** [dotMorten/WinUIEx#73]
This is the same issue as in https://github.com/microsoft/microsoft-ui-xaml/issues/6353
This code:

```csharp
IntPtr hWnd = WindowNative.GetWindowHandle(this);
WindowId wndId = Microsoft.UI.Win32Interop.GetWindowIdFromWindow(hWnd);
var win = AppWindow.GetFromWindowId(wndId);
```

works in the (unpackaged) application, but using `WindowEx` or any method from `WindowManager` crashes with exception 

```
The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Windowing.IAppWindowStaticsMethods.GetFromWindowId(IObjectReference _obj, WindowId windowId)
   at WinUIEx.WindowExtensions.GetAppWindowFromWindowHandle(IntPtr hwnd)
   at WinUIEx.WindowManager..ctor(Window window, WindowMessageMonitor monitor)
```

It looks like `AppWindow.GetFromWindowId(wndId)` has a limited number of usages. Putting the above code in a loop results in an exception within couple of iterations. Could the `AppWindow` instance be cached inside of WindowManager instead of calling this code every time?

Steps to reproduce:
1. Create an app using WinUIEx (you can use Template Studio for WinUI v5.2.1 - https://marketplace.visualstudio.com/items?itemName=TemplateStudio.TemplateStudioForWinUICs )
2. Try to run and restart the (Unpackaged) version of application several times (it usually happens after around 30 debugging sessions after which it doesn't start no more without system restart)

**Comment by dotMorten** [comment]
> Could the AppWindow instance be cached inside of WindowManager instead of calling this code every time?
...
> Try to run and restart the (Unpackaged) version of application several times

I'm not quite following here. You can't cache it across restarts. It would be different each time.

**Comment by dotMorten** [comment]
This to me sounds more like a pretty serious issue the WinAppSDK needs to fix soon. Sure caching it could reduce the likelihood of this happening early on and buy you a little more time, but ultimately running a few WinAppSDK apps and you're in for a full windows restart.   The linked issue above doesn't seem to convey the behavior you're describing.
@rkarman is an upcoming fix for this coming? Sounds pretty serious.

**Comment by PlonkaAdam** [comment]
Just letting know that this error stopped occurring after one of windows updates. I'm still a little concerned about backward compatibility but as I couldn't reproduce this bug for quite a long time, I'm closing this issue for now.
