### ISSUE TITLE
WebAuthenticator adds state parameter incorrectly

### ISSUE THREAD

**Issue by Bondarenko1990** [dotMorten/WinUIEx#75]
I want to add in state parametr provider=1;

        private async void DoOAuth_Click(object sender, RoutedEventArgs e)
        {
            string clientId = "VxIw33TIRCi1Tbk6pjh2i";
            string clientSecret = "eEkUe5e9gUpO6KOYdL5pKTi683LADpi5_izZdHCI8Mndy32B";
            string state = DateTime.Now.Ticks.ToString();
            string callbackUri = "winuiex://";
            string authorizeUri = $"https://www.oauth.com/playground/auth-dialog.html?response_type=code&client_id={clientId}&redirect_uri={Uri.EscapeDataString(callbackUri)}&scope=photo+offline_access&state=provider=1";
            _ = base.ShowMessageDialogAsync("Login: nice-ferret@example.com\npassword: Black-Capybara-83", "Enter credentials in browser");
            var result = await WebAuthenticator.AuthenticateAsync(new Uri(authorizeUri), new Uri(callbackUri));
            Log("Logged in. Code returned: " + result.Properties["code"]);
        }

and in the method Authenticate, we get the old state value "provider=1",
![image](https://user-images.githubusercontent.com/32612104/185210122-6dff81d2-72e1-4b5c-b713-1936f3bd4482.png)
and after that we get query with two state values -"response_type=code&client_id=VxIw33TIRCi1Tbk6pjh2i&redirect_uri=winuiex%3a%2f%2f&scope=photo+offline_access&**state**=appInstanceId%3d6e4168e9-a66a-4258-aae4-2921d57804ff%26signinId%3d9a25feea-f024-4430-8528-75cef7132cdd%26**state**%3dprovider%253d1"
![image](https://user-images.githubusercontent.com/32612104/185211609-349d1bb9-c047-4ba1-b76b-8f8a167e497b.png)
I think its need to be remove "state=" and do so
![image](https://user-images.githubusercontent.com/32612104/185211964-a37cb4d7-87e2-47fa-9db7-a857835e623a.png)

**Comment by dotMorten** [comment]
There's only one state parameter. The second one you see is encoded as part of the first one. This happens because the webauthenticator uses the state parameter to resume the correct app session, but if you provide a state parameter as well, it will be encoded into the new state parameter, then decodes it again after the response comes back.

**Comment by Bondarenko1990** [comment]
> **state**=appInstanceId%3d6e4168e9-a66a-4258-aae4-2921d57804ff%26signinId%3d9a25feea-f024-4430-8528-75cef7132cdd%26**state**%3dprovider%253d1

@dotMorten you probably misunderstood me. I understand that the second parameter is encoded in part of the first, but why with the name state if it already exists? `state=appInstanceId%3d6e4168e9-a66a-4258-aae4-2921d57804ff%26signinId%3d9a25feea-f024-4430-8528-75cef7132cdd%26state%3dprovider%253d1`  
why the state parameter contains two state? 

and try add state parametr _provider=1_ to authorizeUri 
string authorizeUri = $"https://www.oauth.com/playground/auth-dialog.html?response_type=code&client_id={clientId}&redirect_uri={Uri.EscapeDataString(callbackUri)}&scope=photo+offline_access&state=provider=1";
System.ArgumentNullException
![image](https://user-images.githubusercontent.com/32612104/185863616-9850ca39-244c-4f46-b3e2-be67a3174949.png)

**Comment by dotMorten** [comment]
> why with the name state if it already exists?

Because it's part of the oauth standard to use `state` as a parameter for roundtripping back to the redirect. Most oauth services will strip all other parameters when getting to the redirect.

**Comment by dotMorten** [comment]
btw your string is encoded incorrectly: `&state=provider=1)";` Shouldn't that second `=` be encoded?

**Comment by Bondarenko1990** [comment]
>

**Comment by Bondarenko1990** [comment]
> > why with the name state if it already exists?
> 
> Because it's part of the oauth standard to use `state` as a parameter for roundtripping back to the redirect. Most oauth services will strip all other parameters when getting to the redirect.

yes, but why we do we have to set 'state' twice?

**Comment by Bondarenko1990** [comment]
> btw your string is encoded incorrectly: `&state=provider=1`. Shouldn't that second `=` be encoded?

I tried
![image](https://user-images.githubusercontent.com/32612104/186688223-a696ec4f-e189-4973-87a7-0a3cea5ee350.png)
and got a bad result. application relaunched

**Comment by Bondarenko1990** [comment]
> > btw your string is encoded incorrectly: `&state=provider=1`. Shouldn't that second `=` be encoded?
> 
> I tried ![image](https://user-images.githubusercontent.com/32612104/186688223-a696ec4f-e189-4973-87a7-0a3cea5ee350.png) and got a bad result. application relaunched

@dotMorten  Have you tasted?

**Comment by dotMorten** [comment]
> yes, but why we do we have to set 'state' twice?
> `state=appInstanceId%3d6e4168e9-a66a-4258-aae4-2921d57804ff%26signinId%3d9a25feea-f024-4430-8528-75cef7132cdd%26state%3dprovider%253d1`

Again the state isn't set twice. It is set once, and there happen be the string `state%3d` in there.

**Comment by dotMorten** [comment]
It does look like the oauth playground service has changed and is no longer correctly preserving encoding of the state parameter. This is a service issue, and not a WinUIEx issue though - I'll have to find a different service to use as an example, but if you use a proper oauth service this shouldn't be a problem for you
