### ISSUE TITLE
Compatibility with net6.0

### ISSUE THREAD

**Issue by rehali** [dotMorten/WinUIEx#76]
Trying to use WinUIEx on a new net6.0 app I get the following error:

Error	NU1202	Package WinUIEx 1.8.0 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package WinUIEx 1.8.0 supports: net5.0-windows10.0.18362 (.NETCoreApp,Version=v5.0)

**Comment by dotMorten** [comment]
WinUI requires net6.0-windows10.0.19041+
