### ISSUE TITLE
Strange color behaviour when using 'CenterOnScreen'

### ISSUE THREAD

**Issue by mavado83** [dotMorten/WinUIEx#77]
Hi, thanks for the great project. Keeping me away from using nativemethods.  

I noticed strange color behaviour when changing the selected theme to dark when using the CenterOnScreen extension method. 

Background:

Using the lastest Template Studio for WinUI (where WinUIEx is included). Generated a clean template with the theme selector (available in settings) 
Using VS 2022 on Windows 11

Setting the window using: ` App.MainWindow.CenterOnScreen(800, 600);`

Issue:

When running the default template, there're no issues, but when using the CenterOnScreen feature the colors are messed up when selecting the dark theme. See the screenshot below: 

![image](https://user-images.githubusercontent.com/6151556/187444535-92faa522-7fb4-489d-a20e-fc373bba110d.png)

Without the CenterOnScreen:

![image](https://user-images.githubusercontent.com/6151556/187444830-9f33fa35-b1a6-4145-b19b-2234094e7db0.png)

**Comment by dotMorten** [comment]
At what point are you calling this method? Does it still happen if you delay the call? The method you're calling is just calling into a standard Windows API to place and size a window, so it's likely a WinUI bug and less likely a WinUIEx issue.

**Comment by dotMorten** [comment]
Closing due to lack of information to repro / stale issue
