### ISSUE TITLE
Is there any chance to add Closing events for the window class in the future?

### ISSUE THREAD

**Issue by Gaoyifei1011** [dotMorten/WinUIEx#84]
目前微软在Winui3中只为窗口类中提供了Closed事件，这一事件只有在窗口关闭后才会发生，并不会在窗口关闭时发生。如果我想在关闭窗口时添加一个提醒对话框提醒用户是否确认关闭窗口，只能通过自定义一个Closing事件完成相应的操作，未来WinuiEx会有机会支持这个操作吗？
Currently, Microsoft only provides Closed events in Windows classes in Winui3. This event only occurs after the window is closed, not when it is closed. If I want to add a reminder dialog box to remind the user whether to confirm Closing the window when I close the window, I can only finish the corresponding operation by defining a closing event. Will WinuiEx have the chance to support this operation in the future?  
![image](https://user-images.githubusercontent.com/49179966/197089961-17b762cb-6dc7-4c6b-8f2e-6ee5aa37ea7e.png)
例图：记事本关闭窗口时提醒用户是否要保存未完成编辑的更改
Example diagram: Notepad closes the window to remind the user whether to save pending edited changes

**Comment by rocksdanister** [comment]
Currently closed is actually closing https://github.com/microsoft/microsoft-ui-xaml/issues/5454

Set [Handled](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.windoweventargs.handled?view=windows-app-sdk-1.1#microsoft-ui-xaml-windoweventargs-handled) to true to cancel.

**Comment by dotMorten** [comment]
Thanks @rocksdanister for beating me to it
