### ISSUE TITLE
Native SplashScreen

### ISSUE THREAD

**Issue by rocksdanister** [dotMorten/WinUIEx#87]
WinUI can take time to start, one solution although limited would be to implement native impl similar to wpf:

>The [SplashScreen](https://learn.microsoft.com/en-us/dotnet/api/system.windows.splashscreen?view=windowsdesktop-7.0) class displays the splash screen as soon as possible after the application is started. The splash screen is displayed by using native code, before the WPF application instance is created. The splash screen is displayed in the center of the screen. When the application is loaded, the splash screen fades.

Example:
https://github.com/castorix/WinUI3_SplashScreen

**Comment by dotMorten** [comment]
I’m not quite getting your point here? You want an image to show faster?
The purpose of WinUIEx’s splash screen is to provide an interactive dialog showing progress etc

**Comment by rocksdanister** [comment]
In low end systems winui takes time to show ui once you use self-contained runtime etc, so instead of initialising and using winui window for splashscreen it is faster to use native method.

**Comment by dotMorten** [comment]
I've asked @castorix for permission to port his work to here.
