### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by AlonAm** [dotMorten/WinUIEx#9]
Is it available as NuGet Package?
Thank you!

**Comment by kotx** [comment]
Bump, would appreciate if this was added.

**Comment by Xiaohui2333** [comment]
Echo you, hope to access it in NuGet!
Thanks you!

**Comment by AlonAm** [comment]
@dotMorten lemme know if you need help with that...

**Comment by dotMorten** [comment]
No help needed. It's not that it isn't easy to do, but that this entire project is heavily in flux, constantly changing, and so is the underlying Windows Apps SDK. I'd like to get to a 1.0 of WAS before committing to this bit. Having said that I recently made an `EXPERIMENTAL` conditional so at least the most unstable parts are easily compiled out, as one stop to get closer to this.

**Comment by byrialsen** [comment]
Hi @dotMorten. Any update aften release 1.0?

**Comment by dotMorten** [comment]
Working on it, but very little time currently to wrap it up. Main branch is at least building now, but want to do some major API clean up first before shipping, since they removed quite a lot, and things are quite messy at this point.

**Comment by dotMorten** [comment]
Here ya go: https://www.nuget.org/packages?q=WinUIEx
