### ISSUE TITLE
Bug: `DarkTintOpacity` breaks mica backdrop on dark mode

### ISSUE THREAD

**Issue by yaira2** [dotMorten/WinUIEx#91]
## Description
Modifying the `DarkTintOpacity` causes mica to be applied incorrectly on dark mode.

### Steps to repro
1. Create a `MicaSystemBackdrop` in xaml and change the `DarkTintOpacity` value. This issue is only present when you set a custom `DarkTintOpacity`. 
```xml
<winuiex:WindowEx.Backdrop>
	<winuiex:MicaSystemBackdrop DarkTintOpacity="0.8"/>
</winuiex:WindowEx.Backdrop>
```

### Screenshot
![image](https://user-images.githubusercontent.com/39923744/206526227-9887639d-2532-46a9-8afd-9ee56bf8cce8.png)

### Version
This issue was introduced in v2.0

**Comment by dotMorten** [comment]
Something SUPER funky is going on here.
If I step through this method:
https://github.com/dotMorten/WinUIEx/blob/ceacf8752b8645c70fdadfe66fdd6c35240a0c72/src/WinUIEx/SystemBackdrop.cs#L374
it's not an issue. As I'm stepping through it, I notice the default Mica values are changing mid-debugging.
If I delay the call of this method a few 100 ms, the issue goes away too (but that is error prone and also looks terrible).

It's call from the `ActualThemeChanged` event:
https://github.com/dotMorten/WinUIEx/blob/ceacf8752b8645c70fdadfe66fdd6c35240a0c72/src/WinUIEx/WindowManager.Backdrop.cs#L87

It's like WinAppSDK doesn't like some properties to get changed right after a theme change, but considering you'd likely want different backdrop settings for light and dark mode, this is the time to do it.

@ChewWorker @codendone @BenJKuhn Any thoughts on this? Are we not supposed to update backdrop values in the theme changed event?

**Comment by dotMorten** [comment]
WinAppSDK bug. Logged: https://github.com/microsoft/WindowsAppSDK/issues/3230

**Comment by dotMorten** [comment]
Closing now that backdrop APIs are in Windows App SDK and deprecated in WinUIEx

**Comment by yaira2** [comment]
@dotMorten thank you for your work on this issue!
