### ISSUE TITLE
Unable to upgrade to WinUIEx 2.0 with .Net 7.0 in Maui project

### ISSUE THREAD

**Issue by IndianaGary** [dotMorten/WinUIEx#93]
Nuget update failed:

NU1202: Package WinUIEx 2.0.0 is not compatible with net7.0-android33.0 (.NETCoreApp,Version=v7.0). Package WinUIEx 2.0.0 supports: net6.0-windows10.0.18362 (.NETCoreApp,Version=v6.0)

**Comment by dotMorten** [comment]
WinUIEx is only compatible with Windows and that has always been the case. Make sure you only include the package reference for the windows target framework.
