### ISSUE TITLE
MaxWidth inconsistent

### ISSUE THREAD

**Issue by paulober** [dotMorten/WinUIEx#97]
When i set a MaxWidth on the rect from https://learn.microsoft.com/en-us/windows/win32/winmsg/wm-getminmaxinfo WM GETMINMAXINFO window message. It works like expected, you cannot resize the Window more than the MaxWdith: 
```cs
var manager = WindowManager.Get(this);
manager.MinWidth = 1200;
manager.MaxWidth = 1600;
```
for example.
If you now click the maximize window button it only maximizes until the maxwidth is reached what is good. But when you now close and reopen the app it does get fullscreen.

**Comment by dotMorten** [comment]
@paulober I'm assuming you're using window location persistence?
